# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "henriquelalves"
description:        "projects, posts and ideas from me"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//henriquelalves.github.io"
author:             "henriquelalves"
twitter:
  username:         "gfjaru"

#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Sass
sass:
  style:            :compressed

# Github Authentication
repository: henriquelalves/henriquelalves.github.io

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
      author:       "Henrique L. Alves"
      lead:         ""
      tags:         ""

gems:
  - jekyll-seo-tag
